
controller: controller.c
	gcc -o controller $< -lbluetooth

sender: sender.c
	gcc -o sender $< -lhiredis

simplescan: simplescan.c
	gcc -o simplescan $< -lbluetooth

readwrite: readwrite.c
	gcc -o readwrite $< -lbluetooth
